version: '3'
services:
  green:
    build:
      context: .
      dockerfile: Dockerfile.green14
    ports:
      - "8081:8080"  # Expose a different port for the green environment
    # Add other configurations specific to the green environment

